controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true # set false for real robot

    joint_trajectory_controller: 
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_wheel_hinge
      - right_wheel_hinge
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity